// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2l3QGCG10OHExENoanoe0IPTvx_s_aCw',
    appId: '1:820304575334:web:4b33f985e32adfdd49e6a7',
    messagingSenderId: '820304575334',
    projectId: 'chat-app-8df2f',
    authDomain: 'chat-app-8df2f.firebaseapp.com',
    storageBucket: 'chat-app-8df2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwMzrnZGtSCQNHOULMQyS1UwPpGHS1kYw',
    appId: '1:820304575334:android:b6a996b02390702e49e6a7',
    messagingSenderId: '820304575334',
    projectId: 'chat-app-8df2f',
    storageBucket: 'chat-app-8df2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNnUA_u_NtpdR7GZfh8djUWAxOAot1z14',
    appId: '1:820304575334:ios:f19db9235ad6854649e6a7',
    messagingSenderId: '820304575334',
    projectId: 'chat-app-8df2f',
    storageBucket: 'chat-app-8df2f.appspot.com',
    iosClientId: '820304575334-56ph43hlmt7mi348epjnm1mv5onnqrqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
